### ISSUE TITLE
Fix image sprite on high res screen

### ISSUE THREAD

**Issue by mikethone** [awonak/liquorpark#18]
Need to update Main.css (555) to this:

@media (-webkit-min-device-pixel-ratio: 2),
(min-resolution: 192dpi) {
    /\* Retina-specific stuff here */
    .sprite {
        background-size: 200px 150px;
        background-image: url('../img/LiquorPark_Sprite_2x.png');
    }
}

**Comment by awonak** [comment]
merged, looks good!
